###############################################################################
# Dock
###############################################################################
#
# Interface to a mock docking controller
#
###############################################################################

####################
# Goal
####################
# To dock (True) or undock (False)
bool dock

---
####################
# Result
####################

string message

---

####################
# Feedback
####################

float32 percentage_completed
