# Open a private stream for snapshots

# Publish periodically every 2.0s or only on tree state changes
bool publish_periodically
bool with_blackboard_data
bool with_blackboard_activity
bool with_statistics

---

# topic name that is dynamically created for streaming
string topic
