# Reconfigure a snapshot stream

string topic

# Publish periodically every 2.0s or only on tree state changes
bool publish_periodically
bool with_blackboard_data
bool with_blackboard_activity
bool with_statistics

---
# response stating successful shutdown of sub_blackboard
bool result
